import { Project } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: '神经修复项目',
    phase: '临床二期',
    pos: 50,
    marketPotential: 12,
    budget: 450,
    strategicScore: 85,
    toxicityRisk: false,
    confidence: 0.9,
    patentLife: 12,
    rdCost: 320,
    description: '针对早期阿尔茨海默症的新一代神经再生疗法。',
    predictions: [
      { year: 2026, phase: '临床二期', marketShare: 0 },
      { year: 2027, phase: '临床三期', marketShare: 2 },
      { year: 2028, phase: '临床三期', marketShare: 5 },
      { year: 2029, phase: 'NDA 申报', marketShare: 12 },
      { year: 2030, phase: '已上市', marketShare: 25 },
    ]
  },
  {
    id: '2',
    name: '心血管药物',
    phase: '临床一期',
    pos: 70,
    marketPotential: 8,
    budget: 280,
    strategicScore: 70,
    toxicityRisk: true,
    confidence: 0.4,
    patentLife: 15,
    rdCost: 150,
    description: '用于慢性心力衰竭管理的小分子抑制剂。',
    predictions: [
      { year: 2026, phase: '临床一期', marketShare: 0 },
      { year: 2027, phase: '临床二期', marketShare: 0 },
      { year: 2028, phase: '临床二期', marketShare: 1 },
      { year: 2029, phase: '临床三期', marketShare: 3 },
      { year: 2030, phase: '临床三期', marketShare: 8 },
    ]
  },
  {
    id: '3',
    name: '肿瘤疫苗平台',
    phase: '临床三期',
    pos: 30,
    marketPotential: 22,
    budget: 850,
    strategicScore: 92,
    toxicityRisk: false,
    confidence: 0.85,
    patentLife: 8,
    rdCost: 680,
    description: '使用 mRNA 技术的个性化癌症疫苗平台。',
    predictions: [
      { year: 2026, phase: '临床三期', marketShare: 5 },
      { year: 2027, phase: 'NDA 申报', marketShare: 15 },
      { year: 2028, phase: '已上市', marketShare: 35 },
      { year: 2029, phase: '已上市', marketShare: 45 },
      { year: 2030, phase: '已上市', marketShare: 55 },
    ]
  },
  {
    id: '4',
    name: '免疫基因疗法',
    phase: '临床前',
    pos: 20,
    marketPotential: 18,
    budget: 120,
    strategicScore: 65,
    toxicityRisk: false,
    confidence: 0.3,
    patentLife: 18,
    rdCost: 80,
    description: '用于罕见自身免疫性疾病的基因编辑工具。',
    predictions: [
      { year: 2026, phase: '临床前', marketShare: 0 },
      { year: 2027, phase: '临床一期', marketShare: 0 },
      { year: 2028, phase: '临床一期', marketShare: 0 },
      { year: 2029, phase: '临床二期', marketShare: 0 },
      { year: 2030, phase: '临床二期', marketShare: 2 },
    ]
  },
  {
    id: '5',
    name: '呼吸系统替代药',
    phase: '临床二期',
    pos: 45,
    marketPotential: 5,
    budget: 310,
    strategicScore: 55,
    toxicityRisk: true,
    confidence: 0.95,
    patentLife: 10,
    rdCost: 240,
    description: '用于重症哮喘的吸入性皮质类固醇替代品。',
    predictions: [
      { year: 2026, phase: '临床二期', marketShare: 0 },
      { year: 2027, phase: '临床二期', marketShare: 2 },
      { year: 2028, phase: '临床三期', marketShare: 5 },
      { year: 2029, phase: '临床三期', marketShare: 10 },
      { year: 2030, phase: 'NDA 申报', marketShare: 15 },
    ]
  }
];
